name: CI Pipeline for Project

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Make tests.sh executable
        run: chmod +x ./tests.sh

      - name: Run tests
        run: ./tests.sh
        env:
          MOCK_DATA: true  

      - name: Workflow Status
        run: echo "Workflow completed with status ${{ job.status }}"
